$ErrorActionPreference = "Stop"

function Assert-Contains {
  param(
    [string]$Path,
    [string]$Pattern,
    [string]$Message
  )

  $content = Get-Content -Raw -Encoding UTF8 $Path
  if ($content -notmatch $Pattern) {
    throw $Message
  }
}

function Assert-NotContains {
  param(
    [string]$Path,
    [string]$Pattern,
    [string]$Message
  )

  $content = Get-Content -Raw -Encoding UTF8 $Path
  if ($content -match $Pattern) {
    throw $Message
  }
}

function Assert-NoFiles {
  param(
    [string]$Path,
    [string]$Message
  )

  if ((Test-Path $Path) -and (Get-ChildItem -Path $Path -File | Measure-Object).Count -gt 0) {
    throw $Message
  }
}

$requiredPages = @(
  "_pages/about.md",
  "_pages/research.md",
  "_pages/teaching.md",
  "_pages/service.md",
  "_pages/miscellaneous.md"
)

foreach ($page in $requiredPages) {
  if (!(Test-Path $page)) {
    throw "Missing required page: $page"
  }
}

Assert-Contains "_pages/about.md" "title:\s*Home" "Homepage nav title should be Home."
Assert-Contains "_pages/about.md" "Good morning, and in case I don't see you, good afternoon, good evening, and good night!" "Homepage should use the previous subtitle from master."
Assert-NotContains "_pages/about.md" "subtitle:\s*Assistant Professor, CUHK Business School" "Homepage subtitle should not repeat the job title."
Assert-Contains "_pages/about.md" "profile_layout:\s*hero" "Homepage should use the profile hero layout."
Assert-Contains "_pages/about.md" "home_intro:" "Homepage should keep the short bio in the profile hero."
Assert-Contains "_pages/about.md" "During my Ph\.D\., I was very fortunate to be advised by \[Zuo-Jun Max Shen\]\(https://zj-maxshen.github.io/\), and throughout my journey I have been shaped by many people I have had the privilege to learn from, including my friends, coauthors, colleagues, and students\." "Homepage bio should use the approved advisor-and-community sentence."
Assert-NotContains "_pages/about.md" "Along the way, my thinking has been shaped" "Homepage bio should not keep the rejected older community sentence."
Assert-Contains "_pages/about.md" "Having been shaped by so many people has made me especially interested in how influence travels and how seemingly local actions can have effects far beyond where they begin\." "Homepage bio should use the approved influence-travels language."
Assert-Contains "_pages/about.md" "This perspective shapes the questions I study in operations management: how decisions are connected, how their effects spread across people and systems, and how we can design better decisions in an interconnected world\." "Homepage bio should end with the integrated operations-management philosophy."
Assert-NotContains "_pages/about.md" "A store location can redirect attention|a platform policy can change who gets seen|an AI recommendation can reshape what people learn to do next|chain reactions" "Homepage bio should not keep the older example-heavy wording."
Assert-NotContains "_pages/about.md" "My research sits at the intersection" "Homepage bio should avoid mechanical research-position phrasing."
Assert-NotContains "_pages/about.md" "I study how decisions travel:" "Homepage bio should avoid list-like research phrasing."
Assert-Contains "_pages/about.md" "home_contact:" "Homepage should keep contact information in the left profile hero column."
Assert-NotContains "_pages/about.md" "home_contact:\s*\r?\n\s*-\s*Department of Decisions, Operations and Technology" "Homepage contact card should not repeat the department as its first line."
Assert-Contains "_pages/about.md" "\*\*Office:\*\* 9/F, Cheng Yu Tung Building" "Homepage contact card should include the office address without a room number."
Assert-NotContains "_pages/about.md" "Room 950" "Homepage contact card should not include Room 950."
Assert-Contains "_pages/about.md" "\*\*Email:\*\* yunduanlin\[at\]cuhk\[dot\]edu\[dot\]hk" "Homepage contact card should explicitly label the email address."
Assert-Contains "_pages/about.md" "If you have shared interests, please feel free to reach out!" "Homepage contact card should include the approved reach-out sentence."
Assert-NotContains "_pages/about.md" "Welcome to reach out about:|I am happy to hear from students and researchers interested in connected decision-making" "Homepage contact card should avoid older reach-out wording."
Assert-Contains "_pages/about.md" "Assistant Professor" "Homepage should use the current Assistant Professor title."
Assert-Contains "_pages/about.md" "Assistant Professor, Department of Decisions, Operations and Technology" "Homepage employment should spell out the department name."
Assert-NotContains "_pages/about.md" "Assistant Professor,\s*DOT" "Homepage employment should not use the DOT abbreviation."
Assert-Contains "_pages/about.md" "CUHK Business School" "Homepage should identify CUHK Business School."
Assert-Contains "_pages/about.md" "Department of Decisions, Operations and Technology" "Homepage should identify the current department."
Assert-NotContains "_pages/about.md" "will be joining|fifth-year Ph\.D\. candidate" "Homepage still contains stale career-stage language."
Assert-NotContains "_pages/about.md" "I received my Ph\.D\. and M\.S\." "Homepage intro should not lead with education history."
Assert-Contains "_pages/about.md" "news:\s*false" "Homepage should not render the news section."
Assert-NotContains "_pages/about.md" "selected_papers:\s*true" "Homepage should not render selected publications."
Assert-NotContains "_pages/about.md" "/publications/|/cv/|CV\.pdf" "Homepage should not link to removed publications or CV pages."
Assert-NotContains "_pages/about.md" "<div class=""clearfix""></div>" "Homepage should not force research content below the profile image."
Assert-NotContains "_layouts/about.liquid" "/news/" "About layout should not contain a dormant news section link."
Assert-NotContains "_layouts/about.liquid" "selected publications|selected_papers" "About layout should not render the selected publications block."
Assert-Contains "_layouts/about.liquid" "home-page" "About layout should expose a homepage-specific styling hook."
Assert-Contains "_layouts/about.liquid" "home-profile-hero" "About layout should support the homepage profile hero."
Assert-Contains "_layouts/about.liquid" "home-profile-img" "Homepage portrait should render as a direct image for reliable preview display."
Assert-Contains "_layouts/about.liquid" "home-contact-card" "About layout should render the contact block as a dedicated card."
Assert-Contains "_layouts/about.liquid" "home-contact-line-primary" "About layout should distinguish the first contact card line."
Assert-Contains "_layouts/about.liquid" "home-contact-line-invite" "Homepage contact card should give the final invitation line a special class."
Assert-Contains "_layouts/about.liquid" "forloop\.last" "Homepage contact card should style the invitation as the final contact line."
Assert-Contains "_layouts/about.liquid" "(?s)<aside class=""profile home-profile-photo"">.*</aside>\s*\{% if page\.home_contact %\}" "Homepage contact card should sit after the portrait so it can span the full hero grid."
Assert-Contains "_layouts/default.liquid" "site_network_watermark\.liquid" "Default layout should include the faded graph monogram watermark."
if (!(Test-Path "assets/img/network-watermark-fluent-lin.png")) {
  throw "Missing selected fluent-LIN network watermark image."
}
Assert-Contains "_includes/site_network_watermark.liquid" "site-network-watermark" "Watermark include should define the graph artwork wrapper."
Assert-Contains "_includes/site_network_watermark.liquid" "<img" "Watermark should use the selected fluent-LIN network artwork."
Assert-Contains "_includes/site_network_watermark.liquid" "assets/img/network-watermark-fluent-lin\.png" "Watermark should reference the selected fluent-LIN network artwork asset."
Assert-Contains "_includes/site_network_watermark.liquid" "alt=""""" "Watermark image should be decorative and empty-alt."
Assert-NotContains "_includes/site_network_watermark.liquid" "<svg|site-network-edge|site-network-node" "Watermark include should not keep the older inline SVG graph."
Assert-Contains "_sass/_layout.scss" "\.site-network-watermark" "Layout styles should define the fluent-LIN network watermark."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark\s*\{[^}]*position:\s*fixed" "Watermark should sit as a fixed background decoration."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark.*pointer-events:\s*none" "Watermark should never block page interaction."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark\s*\{[^}]*left:\s*50%" "Watermark should be centered in the page rather than pushed to the right."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark\s*\{[^}]*transform:\s*translateX\(-50%\)" "Watermark should use a centered transform."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark\s*\{[^}]*width:\s*min\(112vw,\s*82rem\)" "Watermark should span the middle of the page."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark\s*\{[^}]*opacity:\s*0\.4" "Watermark should be more visible than the previous faded treatment."
Assert-NotContains "_sass/_layout.scss" "right:\s*max\(" "Watermark should not use the older right-side placement."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark.*img\s*\{[^}]*mix-blend-mode:\s*multiply" "Watermark image should blend softly into the page background."
Assert-Contains "_sass/_layout.scss" "(?s)\.site-network-watermark.*img\s*\{[^}]*filter:" "Watermark image should have a subtle visual treatment."
Assert-Contains "_sass/_layout.scss" "@media \(max-width:\s*767px\)" "Watermark should have a mobile treatment."
Assert-Contains "_sass/_base.scss" "\.home-profile-hero" "Styles should define the homepage profile hero."
Assert-Contains "_sass/_base.scss" "\.home-contact-card" "Styles should define a dedicated homepage contact card."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-card\s*\{[^}]*box-shadow:" "Homepage contact card should use a subtle card shadow."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact\s*\{[^}]*grid-column:\s*1\s*/\s*-1" "Homepage contact card should span both the bio and photo columns."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-card\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)" "Homepage contact card should use one column so each contact item has its own line."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-card\s*\{[^}]*border:\s*1px\s*solid\s*transparent" "Homepage contact card should use a gradient frame rather than a plain border."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-card\s*\{[^}]*background:\s*\r?\n\s*linear-gradient\(115deg,\s*rgba\(117,\s*15,\s*109,\s*0\.045\),\s*rgba\(196,\s*154,\s*44,\s*0\.055\)\)\s*padding-box,\s*\r?\n\s*linear-gradient\(var\(--global-card-bg-color\),\s*var\(--global-card-bg-color\)\)\s*padding-box,\s*\r?\n\s*linear-gradient\(105deg,\s*#750f6d\s*0%,\s*#9d4b8f\s*37%,\s*#c49a2c\s*100%\)\s*border-box" "Homepage contact card should use the selected balanced purple-to-gold gradient frame with a soft interior transition."
Assert-Contains "_sass/_base.scss" "\.home-contact-line-invite" "Homepage contact card should include dedicated invitation-line styling."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-line-invite\s*\{[^}]*border-top:\s*1px\s*solid\s*transparent" "Homepage invitation line should be integrated with a quiet divider."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-line-invite\s*\{[^}]*border-image:\s*linear-gradient\(90deg,\s*rgba\(117,\s*15,\s*109,\s*0\.38\),\s*rgba\(196,\s*154,\s*44,\s*0\.52\)\)\s*1" "Homepage invitation divider should echo the card gradient."
Assert-NotContains "_sass/_base.scss" "(?s)\.home-contact-card\s*\{[^}]*&::before|(?s)\.home-contact-line-invite\s*\{[^}]*display:\s*inline-flex|(?s)&::before,\s*\r?\n\s*&::after" "Homepage contact treatment should not keep the rejected top bar or elegant-line hairline styling."
Assert-Contains "_sass/_base.scss" "(?s)\.home-contact-line-invite\s*\{[^}]*font-weight:\s*650" "Homepage invitation line should not look faded."
Assert-Contains "_sass/_base.scss" "(?s)html\[data-theme=""dark""\]\s*\{.*\.home-profile-hero\s+\.home-contact-card\s*\{[^}]*border-color:\s*transparent" "Dark mode should preserve the gradient contact-card frame."
Assert-NotContains "_sass/_base.scss" "grid-template-columns:\s*minmax\(0,\s*1\.1fr\)\s+minmax\(0,\s*1\.6fr\)\s+minmax\(0,\s*0\.9fr\)" "Homepage contact card should not use the older three-column address layout."
Assert-Contains "_sass/_base.scss" "overflow-wrap:\s*anywhere" "Homepage contact card should wrap long office/email lines safely."
Assert-Contains "_sass/_base.scss" "\.home-page\s+\{" "Styles should define homepage-specific typography and spacing."
Assert-Contains "_sass/_variables.scss" '\$purple-color:\s*#750f6d' "Theme variables should use CUHK-inspired purple."
Assert-Contains "_sass/_variables.scss" '\$gold-color:\s*#c49a2c' "Theme variables should use CUHK-inspired gold."
Assert-Contains "_sass/_variables.scss" '\$gold-color-light:\s*#e1c878' "Theme variables should include a lighter gold for dark mode."
Assert-Contains "_sass/_variables.scss" '\$cyan-color:\s*#e1c878' "Dark mode theme color should stay in the purple-gold family."
Assert-Contains "_sass/_themes.scss" '--global-theme-color:\s*#\{\$purple-color\}' "Light theme should use purple as the primary accent."
Assert-Contains "_sass/_themes.scss" '--global-hover-color:\s*#\{\$gold-color\}' "Light theme hover accent should use gold."
Assert-Contains "_sass/_base.scss" "#c49a2c" "Homepage and research accents should include the CUHK-inspired gold."
Assert-NotContains "_sass/_base.scss" "#1f5fa8|#b8892f|#2f6f6f|#244f4f|#536d8f|#7a5b18" "Custom page styling should not keep the previous blue/green/gold palette."
Assert-NotContains "_sass/_base.scss" "(?s)\.home-profile-intro\s*\{[^}]*border-left:" "Homepage bio intro should not keep the old left accent after contact panel redesign."
Assert-Contains "_sass/_base.scss" "row-gap:\s*1\.4rem" "Mobile homepage hero should keep spacing between intro and portrait."
Assert-Contains "_config.yml" "footer_fixed:\s*false" "Footer should not overlay homepage content."
Assert-Contains "_config.yml" "max_width:\s*1120px" "Site content panel should be wider than the original narrow al-folio default."
Assert-NotContains "_config.yml" "max_width:\s*800px" "Site content panel should not keep the older narrow 800px width."
Assert-Contains "_config.yml" "cloudflare_analytics:\s*1d5a365ec6874492a9aa024ae2c92444" "Cloudflare Web Analytics token should be configured."
Assert-Contains "_config.yml" "enable_cloudflare_analytics:\s*true" "Cloudflare Web Analytics should be enabled."
Assert-Contains "_includes/scripts/analytics.liquid" "static\.cloudflareinsights\.com/beacon\.min\.js" "Analytics include should load the Cloudflare Web Analytics beacon."
Assert-Contains "_includes/scripts/analytics.liquid" "data-cf-beacon" "Analytics include should pass the Cloudflare Web Analytics token."
Assert-Contains "_plugins/cache-bust.rb" "directory:\s*'_sass'" "CSS cache busting should hash the real Sass source directory."
Assert-NotContains "_config.yml" "permalink:\s*/news/:path/|announcements:" "Config should not publish or configure news."
Assert-Contains "_pages/about.md" "####\s*Research Interests" "Homepage should have an organized research interests section."
Assert-Contains "_pages/about.md" "My work begins with the <span>connections around decisions</span>: how choices made by people, platforms, and algorithms <span>shape one another over time</span>\." "Homepage research interests should open with a natural connective framing."
Assert-NotContains "_pages/about.md" "decisions are not isolated events|larger pattern of interaction, adaptation, and feedback" "Homepage research-interest intro should not keep the rejected abrupt statement."
Assert-Contains "_pages/about.md" "Social Network Analytics and Platform Operations" "Homepage should use the approved first research stream title."
Assert-Contains "_pages/about.md" "How do individual choices become collective outcomes\?" "Homepage first stream should include its core question."
Assert-Contains "_pages/about.md" "hidden mechanics of connected markets" "Homepage first stream should use the approved non-KPI description."
Assert-Contains "_pages/about.md" "AI and Machine Learning for Operations" "Homepage should use the approved second research stream title."
Assert-Contains "_pages/about.md" "How can algorithms help us understand systems that are hard to observe directly\?" "Homepage second stream should include its core question."
Assert-Contains "_pages/about.md" "data are imperfect, behavior is adaptive, and decisions unfold over time" "Homepage second stream should use the approved deeper AI/ML description."
Assert-NotContains "_pages/about.md" "My work combines optimization, network and graph models, stochastic simulation, and empirical analysis" "Homepage research description should not read like a methods inventory."
Assert-NotContains "_pages/about.md" "home-philosophy-note|home-research-tags|home-research-tag|decisions have social lives|What happens after one person clicks|What should AI do inside a decision system|AI for operational decision-making|recommendations, adoption, referrals, and content exposure|human experts, AI agents, and public-service systems|design interventions that improve adoption, engagement, allocation" "Homepage research interests should remove the rejected philosophy note, keyword chips, old AI title, and list-like phrasing."
Assert-Contains "_pages/about.md" "home-research-intro" "Homepage research interests should use a dedicated intro line."
Assert-Contains "_pages/about.md" "home-research-themes" "Homepage should render research interests as compact full-width theme blocks."
Assert-Contains "_pages/about.md" "home-research-number" "Homepage research interests should use quiet numbered editorial rows."
Assert-Contains "_pages/about.md" "home-research-body" "Homepage research stream text should be grouped separately from the number."
Assert-Contains "_pages/about.md" "I keep asking" "Homepage research questions should use a softer personal prompt instead of the abrupt core-question label."
Assert-NotContains "_pages/about.md" "Core question:" "Homepage research questions should not use the rejected abrupt core-question label."
Assert-Contains "_pages/about.md" "home-research-question" "Homepage research interests should make each stream's core question visible."
Assert-NotContains "_pages/about.md" "home-research-stream-label|01 / Research stream|02 / Research stream" "Homepage research interests should remove the loud stream-label treatment."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-themes\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)" "Homepage research cards should stack vertically."
Assert-NotContains "_sass/_base.scss" "(?s)\.home-research-themes\s*\{[^}]*grid-template-columns:\s*repeat\(2" "Homepage research cards should not use a two-column layout."
Assert-Contains "_sass/_base.scss" "\.home-research-intro" "Homepage should style the research-interest intro line."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-intro\s*\{[^}]*max-width:\s*none" "Homepage research intro should span the full content panel."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-intro\s*\{[^}]*padding:\s*0\s*0\s*0\.72rem" "Homepage research intro should be a natural lead line instead of a padded banner."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-intro\s*\{.*&::after\s*\{[^}]*background:\s*linear-gradient" "Homepage research intro should use a quiet full-width gradient rule for design."
Assert-NotContains "_sass/_base.scss" "(?s)\.home-research-intro\s*\{[^}]*border-top:\s*1px solid rgba\(117,\s*15,\s*109,\s*0\.18\)|(?s)\.home-research-intro\s*\{[^}]*background:\s*linear-gradient\(90deg,\s*rgba\(117,\s*15,\s*109,\s*0\.065\)" "Homepage research intro should not keep the rejected abrupt banner treatment."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-intro\s*\{.*span\s*\{[^}]*font-weight:\s*760" "Homepage research intro should emphasize the important phrases."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-stream\s*\{[^}]*display:\s*grid" "Homepage research streams should use an editorial row layout."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-stream\s*\{[^}]*grid-template-columns:\s*minmax\(4\.4rem,\s*auto\)\s*minmax\(0,\s*1fr\)" "Homepage research streams should reserve space for oversized faded numbers."
Assert-Contains "_sass/_base.scss" "\.home-research-number" "Homepage should style quiet gold stream numbers."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-number\s*\{[^}]*font-size:\s*clamp\(2\.6rem,\s*5vw,\s*4\.4rem\)" "Homepage research stream numbers should be large and faded."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-number\s*\{[^}]*color:\s*rgba\(117,\s*15,\s*109,\s*0\.12\)" "Homepage research stream numbers should be faded rather than loud."
Assert-Contains "_sass/_base.scss" "\.home-research-body" "Homepage should style the stream body separately from the number."
Assert-Contains "_sass/_base.scss" "\.home-research-question" "Homepage should style core questions distinctly."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-question\s*\{[^}]*display:\s*flex" "Homepage research questions should sit as a designed inline prompt."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-question\s*\{[^}]*font-style:\s*normal" "Homepage research questions should not be italicized."
Assert-Contains "_sass/_base.scss" "(?s)\.home-research-stream\s*\+\s*\.home-research-stream" "Homepage research streams should be separated by quiet dividers."
Assert-NotContains "_sass/_base.scss" "(?s)\.home-research-stream\s*\{[^}]*border-image|(?s)\.home-research-stream\s*\{[^}]*border-left|(?s)\.home-research-question\s*\{[^}]*font-style:\s*italic|home-philosophy-note|home-research-tag|home-research-stream-label|content:\s*attr\(data-index\)" "Homepage styles should remove the rejected vertical rail, italic question, philosophy card, keyword chips, stream label, and faint background numbers."
Assert-Contains "_pages/about.md" "home-timeline-entry" "Homepage should render employment and education as polished timeline rows."
Assert-Contains "_sass/_base.scss" "(?s)\.home-timeline-entry\s*\{[^}]*border-top:\s*1px solid var\(--global-divider-color\)" "Homepage timeline entries should use quiet row dividers."
Assert-NotContains "_sass/_base.scss" "(?s)\.home-timeline-entry\s*\{[^}]*border-left:" "Homepage timeline entries should not use the old research-card accent."
Assert-Contains "_pages/about.md" "home-timeline-date" "Homepage timeline rows should render dates as compact pill labels."
Assert-Contains "_sass/_base.scss" "\.home-timeline-date" "Homepage timeline date pills should be styled explicitly."
Assert-NotContains "_pages/about.md" "<em>2024 - current</em>|<em>2019 - 2024</em>|<em>2018 - 2019</em>|<em>2014 - 2018</em>" "Homepage timeline should not use the older italic date treatment."
Assert-Contains "_pages/about.md" "####\s*Employment" "Homepage should include employment."
Assert-Contains "_pages/about.md" "2024-current" "Homepage employment should include the current CUHK appointment dates."
Assert-Contains "_pages/about.md" "####\s*Education" "Homepage should include education."
Assert-Contains "_pages/about.md" "University of California, Berkeley" "Homepage education should include Berkeley."
Assert-Contains "_pages/about.md" "Tsinghua University" "Homepage education should include Tsinghua."
Assert-NotContains "_pages/about.md" "home-timeline-detail"">Advisor:" "Homepage education timeline should not carry the advisor line."

Assert-Contains "_pages/miscellaneous.md" "title:\s*Miscellaneous" "Miscellaneous page should have the requested page title."
Assert-Contains "_pages/miscellaneous.md" "nav:\s*true" "Miscellaneous page should appear in the top navigation."
Assert-Contains "_pages/miscellaneous.md" "nav_order:\s*5" "Miscellaneous page should appear after Service in the top navigation."
Assert-Contains "_pages/miscellaneous.md" "(?s)<h4 class=""misc-section-heading"">Media Coverage</h4>.*<h4 class=""misc-section-heading"">Selected Honors and Awards</h4>" "Miscellaneous page should lead with Media Coverage before Selected Honors and Awards."
Assert-Contains "_pages/miscellaneous.md" "misc-media-feature" "Miscellaneous media coverage should use a more prominent feature layout."
Assert-Contains "_pages/miscellaneous.md" "https://www\.youtube\.com/embed/YIQK5_F_CBc" "Miscellaneous media coverage should embed the provided YouTube video."
Assert-Contains "_pages/miscellaneous.md" "CUHK Business School Feature" "Miscellaneous media coverage should use a clearer feature label."
Assert-Contains "_pages/miscellaneous.md" "misc-media-meta" "Miscellaneous media coverage should show source and date as explicit metadata."
Assert-Contains "_pages/miscellaneous.md" "misc-link-button" "Miscellaneous media coverage should expose obvious external link buttons."
Assert-Contains "_pages/miscellaneous.md" "Read article" "Miscellaneous media coverage should include an explicit article button."
Assert-Contains "_pages/miscellaneous.md" "Watch video" "Miscellaneous media coverage should include an explicit video button."
Assert-NotContains "_pages/miscellaneous.md" "A China Business Knowledge feature from CUHK Business School discussing how analytics can help anticipate trends" "Miscellaneous media coverage should not include the removed descriptive sentence."
Assert-NotContains "_pages/miscellaneous.md" "misc-media-list|misc-media-item|misc-media-open" "Miscellaneous media coverage should not repeat the same article and video below the feature card."
Assert-Contains "_pages/miscellaneous.md" "tabindex=""0""" "Award rows should be keyboard-focusable so the hover highlight is not mouse-only."
Assert-NotContains "_pages/miscellaneous.md" "misc-award-highlight" "Award highlights should not be hard-coded to selected rows."
Assert-Contains "_pages/miscellaneous.md" "<h4 class=""misc-section-heading"">Selected Honors and Awards</h4>" "Miscellaneous page should include a real Selected Honors and Awards section heading."
Assert-Contains "_pages/miscellaneous.md" "misc-awards-timeline" "Miscellaneous page should use a full visible awards timeline."
Assert-Contains "_pages/miscellaneous.md" "misc-award-item" "Miscellaneous page should render each honor as a clean row."
Assert-Contains "_pages/miscellaneous.md" "misc-award-level" "Miscellaneous awards should separate prize or honor level from competition context."
Assert-Contains "_pages/miscellaneous.md" "misc-award-context" "Miscellaneous awards should separate competition or institution context from the award level."
Assert-Contains "_pages/miscellaneous.md" "(?s)<div class=""misc-award-level"">Finalist</div>\s*<div class=""misc-award-context"">INFORMS Minority Issues Forum Paper Competition</div>" "Miscellaneous page should include the 2024 INFORMS Minority Issues Forum paper finalist honor."
Assert-Contains "_pages/miscellaneous.md" "(?s)<div class=""misc-award-level"">Outstanding Graduate Student Instructor Award</div>\s*<div class=""misc-award-context"">UC Berkeley</div>" "Miscellaneous page should include the Berkeley GSI award."
Assert-Contains "_pages/miscellaneous.md" "(?s)<div class=""misc-award-level"">Winner</div>\s*<div class=""misc-award-context"">INFORMS Social Media Analytics Best Student Paper Award</div>" "Miscellaneous page should include the INFORMS SMA award."
Assert-Contains "_pages/miscellaneous.md" "(?s)<div class=""misc-award-level"">China National Scholarship</div>\s*<div class=""misc-award-context"">Top 1%</div>" "Miscellaneous page should include the China National Scholarship."
Assert-Contains "_pages/miscellaneous.md" "(?s)<div class=""misc-award-level"">Second Prize</div>\s*<div class=""misc-award-context"">National Olympiad in Informatics in Provinces</div>" "Miscellaneous page should include the informatics olympiad award."
Assert-Contains "_pages/miscellaneous.md" "<details class=""misc-awards-more"">" "Awards before 2020 should be hidden initially behind a show-more control."
Assert-Contains "_pages/miscellaneous.md" "<summary class=""misc-awards-more-summary"">" "Earlier-honors control should use the same two-column timeline row structure."
Assert-Contains "_pages/miscellaneous.md" "Before 2020" "Earlier-honors control should label the hidden period in the date column."
Assert-Contains "_pages/miscellaneous.md" "Show more earlier honors" "Awards before 2020 should use a clear show-more label."
Assert-Contains "_pages/miscellaneous.md" "Show fewer earlier honors" "Expanded earlier-honors control should provide a clear collapse label."
Assert-Contains "_pages/miscellaneous.md" "(?s)<time class=""misc-award-date"">Oct 2022</time>.*<details class=""misc-awards-more"">.*<time class=""misc-award-date"">Nov 2017</time>" "Awards before 2020 should appear only inside the earlier-honors details block."
Assert-NotContains "_pages/miscellaneous.md" "Departmental Award|Graduate Division Conference Travel Grant|Tsinghua-Evergrande|Tsinghua-Zhenli" "Miscellaneous page should omit commented-out CV awards and the two removed Tsinghua corporate scholarship rows."
Assert-NotContains "_pages/miscellaneous.md" "Academic and Research Honors|Undergraduate Honors|Earlier Competitions|####|\\{:\s*\.misc-section-heading\s*\\}" "Miscellaneous page should not show raw markdown headings or highlighted subgroup labels."
Assert-Contains "_pages/miscellaneous.md" "https://www\.youtube\.com/watch\?v=YIQK5_F_CBc" "Miscellaneous media coverage should include the provided YouTube video link."
Assert-Contains "_pages/miscellaneous.md" "https://cbk\.bschool\.cuhk\.edu\.hk/how-to-forecast-trends-amid-uncertainty/" "Miscellaneous media coverage should include the provided CUHK China Business Knowledge article link."
Assert-Contains "_pages/miscellaneous.md" "How to forecast trends amid uncertainty" "Miscellaneous media coverage should use the verified media coverage title."
Assert-Contains "_pages/miscellaneous.md" "China Business Knowledge, CUHK Business School" "Miscellaneous media coverage should identify the CUHK article source."
Assert-Contains "_sass/_base.scss" "\.misc-section-heading" "Styles should define the miscellaneous section heading."
Assert-Contains "_sass/_base.scss" "\.misc-awards-timeline" "Styles should define the full awards timeline."
Assert-Contains "_sass/_base.scss" "\.misc-award-item" "Styles should define compact award rows."
Assert-Contains "_sass/_base.scss" "(?s)\.misc-media-feature\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)" "Media coverage feature should stack the video and copy into two rows."
Assert-NotContains "_sass/_base.scss" "grid-template-columns:\s*minmax\(0,\s*1\.1fr\)\s*minmax\(18rem,\s*0\.9fr\)" "Media coverage should not use the cramped two-column layout."
Assert-Contains "_sass/_base.scss" "\.misc-award-item:hover" "Styles should reveal award emphasis on hover instead of choosing permanent highlighted rows."
Assert-Contains "_sass/_base.scss" "\.misc-award-item:focus" "Styles should reveal award emphasis on keyboard focus as well as hover."
Assert-NotContains "_sass/_base.scss" "\.misc-award-highlight" "Award highlight styling should be interaction-based, not hard-coded to selected rows."
Assert-Contains "_sass/_base.scss" "\.misc-award-date" "Styles should define gold award date labels."
Assert-Contains "_sass/_base.scss" "\.misc-award-level" "Styles should define award level text."
Assert-Contains "_sass/_base.scss" "\.misc-award-context" "Styles should define award context text."
Assert-Contains "_sass/_base.scss" "\.misc-awards-more" "Styles should define the earlier-honors show-more block."
Assert-Contains "_sass/_base.scss" "\.misc-awards-more\s*>\s*summary" "Styles should define the earlier-honors show-more control."
Assert-Contains "_sass/_base.scss" "\.misc-awards-more-label::before" "Earlier-honors plus/minus icon should live inside the content pill, not on the timeline marker."
Assert-Contains "_sass/_base.scss" "\.misc-awards-more\s*\[open\]\s*\.misc-more-open-label" "Expanded earlier-honors control should swap to the collapse label."
Assert-Contains "_sass/_base.scss" "\.misc-awards-more\s*>\s*summary::before" "Earlier-honors control should keep a separate timeline marker."
Assert-NotContains "_sass/_base.scss" "(?s)\.misc-award-date\s*\{[^}]*background-color|(?s)\.misc-award-date\s*\{[^}]*border-left:\s*2px" "Award dates should not keep the rejected heavy time-panel styling."
Assert-Contains "_sass/_base.scss" "\.misc-award-item::before" "Awards should use a subtle timeline marker instead of repeated group-card headers."
Assert-Contains "_sass/_base.scss" "(?s)\.misc-awards-timeline\s*\{[^}]*border-left:" "Awards should read as one timeline with a quiet vertical rule."
Assert-NotContains "_sass/_base.scss" "\.misc-awards-panel|\.misc-awards-group|\.misc-awards-group-title|overflow-y:\s*auto" "Awards should not keep the rejected scroll panel or subgroup card styles."
Assert-Contains "_sass/_base.scss" "\.misc-media-feature" "Styles should define the media feature layout."
Assert-Contains "_sass/_base.scss" "\.misc-video-frame" "Styles should define the embedded video frame."
Assert-Contains "_sass/_base.scss" "\.misc-media-meta" "Styles should define the media feature metadata line."
Assert-Contains "_sass/_base.scss" "\.misc-link-button" "Styles should define obvious media link buttons."
Assert-Contains "_sass/_base.scss" "\.misc-media-title" "Styles should define readable media coverage titles."
Assert-NotContains "_sass/_base.scss" "\.misc-media-list|\.misc-media-item|\.misc-media-open|\.misc-media-date|\.misc-media-source" "Styles should remove the old duplicate media-row selectors."
Assert-Contains "README.md" "miscellaneous" "README should describe the current page structure including miscellaneous."

Assert-Contains "_pages/service.md" "####\s*Industry Experience" "Service page should include the Industry Experience section."
Assert-Contains "_pages/service.md" "(?s)Didi.*Academic Consultant.*DiDi Marketplace, Beijing.*06/2025\s*-\s*present" "Industry Experience should include the Didi academic consultant role."
Assert-Contains "_pages/service.md" "(?s)Amazon.*Research Scientist Intern II.*Middle Mile Product Team, Seattle, WA.*06/2021\s*-\s*08/2021" "Industry Experience should include the Amazon internship."
Assert-Contains "_pages/service.md" "(?s)Kuaishou.*Data Scientist Intern.*Data Science and Economist Team, Beijing.*06/2019\s*-\s*06/2020" "Industry Experience should include the Kuaishou internship."
Assert-Contains "_pages/service.md" "service-experience-list" "Industry Experience should use compact custom service markup."
Assert-Contains "_sass/_base.scss" "\.service-experience-list" "Styles should define the service experience list."
Assert-Contains "_sass/_base.scss" "\.service-experience-date" "Styles should define service experience date labels."
Assert-NotContains "_pages/service.md" "Manager: Ivan Oliveira|Mentor: Golbarg Tutunchi|Developed algorithms" "Industry Experience should omit commented CV details from the public service page."
Assert-Contains "_pages/service.md" "####\s*Academic Services" "Service page should include Academic Services."
Assert-Contains "_pages/service.md" "service-academic-panel" "Academic Services should use a structured custom service panel."
Assert-Contains "_pages/service.md" "Ad-Hoc Journal Reviewer" "Academic Services should include the Ad-Hoc Journal Reviewer subsection."
Assert-Contains "_pages/service.md" "Management Science" "Journal reviewer list should include Management Science."
Assert-Contains "_pages/service.md" "Operations Research" "Journal reviewer list should include Operations Research."
Assert-Contains "_pages/service.md" "Manufacturing &amp; Service Operations Management" "Journal reviewer list should include M&SOM."
Assert-Contains "_pages/service.md" "Production and Operations Management" "Journal reviewer list should include POM."
Assert-Contains "_pages/service.md" "Naval Research Logistics" "Journal reviewer list should include Naval Research Logistics."
Assert-Contains "_pages/service.md" "Accident Analysis and Prevention" "Journal reviewer list should include Accident Analysis and Prevention."
Assert-Contains "_pages/service.md" "Transportation Research Part E" "Journal reviewer list should include Transportation Research Part E."
Assert-NotContains "_pages/service.md" "<em>Management Science</em>|<em>Operations Research</em>|<em>Manufacturing &amp; Service Operations Management</em>|<em>Production and Operations Management</em>|<em>Naval Research Logistics</em>|<em>Accident Analysis and Prevention</em>|<em>Transportation Research Part E</em>" "Journal reviewer names should be plain text, not italicized."
Assert-Contains "_pages/service.md" "Workshop and Conference Reviewer" "Academic Services should include workshop and conference reviewing."
Assert-Contains "_pages/service.md" "(?s)Workshop and Conference Reviewer.*<p class=""service-text-list"">\s*INFORMS Data Science Workshop 2026, ICIS 2026\s*</p>" "Workshop reviewer list should be a plain text line like the journal list."
Assert-Contains "_pages/service.md" "Competition Judge" "Academic Services should include competition judging."
Assert-Contains "_pages/service.md" "(?s)Competition Judge.*<p class=""service-text-list"">\s*POMS-HK Best Student Paper Competition 2025/2026, INFORMS Service Science Best Cluster Paper Award Competition 2025/2026\s*</p>" "Competition judge list should be a plain text line like the reviewer lists."
Assert-Contains "_pages/service.md" "service-text-list" "Academic Services should use readable text lists instead of chip-only rows."
Assert-NotContains "_pages/service.md" "service-compact-row|service-compact-rows" "Competition judge should not use highlighted compact rows."
Assert-NotContains "_pages/service.md" "POMS-HK 2026 Best Student Paper Competition|POMS-HK 2025 Best Student Paper Competition|2025 INFORMS Service Science Best Cluster Paper Award Competition" "Competition judge entries should not keep the unmerged year-specific chips."
Assert-Contains "_pages/service.md" "(?s)</div>\s*####\s*Internal Services" "Internal Services should be a peer section after Academic Services, not nested inside it."
Assert-Contains "_pages/service.md" "service-internal-panel" "Internal Services should use its own structured panel."
Assert-Contains "_pages/service.md" "service-internal-group" "Internal Services should be grouped by institution."
Assert-Contains "_pages/service.md" "The Chinese University of Hong Kong" "Internal Services should include a CUHK group."
Assert-Contains "_pages/service.md" "University of California, Berkeley" "Internal Services should include a Berkeley group."
Assert-Contains "_pages/service.md" "(?s)Seminar Coordinator.*Department of Decisions, Operations and Technology.*2025-2027" "Internal services should format the CUHK seminar coordinator as role, full department, date."
Assert-Contains "_pages/service.md" "(?s)PhD Interview Committee.*Department of Decisions, Operations and Technology.*2024-2026" "Internal services should format the CUHK PhD interview committee as role, full department, date."
Assert-Contains "_pages/service.md" "(?s)Co-founder &amp; Secretary, Representation of Asian and Pacific Islanders.*CEE Department.*05/2023\s*-\s*05/2024" "Berkeley internal service should format the RAPI row as role plus committee, unit, date."
Assert-Contains "_pages/service.md" "(?s)Student Representative, Graduate Studies Committee.*College of Engineering.*10/2022\s*-\s*10/2023" "Berkeley internal service should format the Graduate Studies Committee row as role plus committee, unit, date."
Assert-NotContains "_pages/service.md" "DOT Department" "Service page should spell out the DOT department name where it appears."
Assert-NotContains "_pages/service.md" "(?s)Representation of Asian and Pacific Islanders.*Co-founder &amp; Secretary|(?s)Graduate Studies Committee.*Student Representative" "Berkeley internal service should not put the committee before the role."
Assert-NotContains "_pages/service.md" "####\s*Berkeley Service|Conference Session Chair|Management Science Reproducibility Project|Co-Chair, &ldquo;Social Network and Platform Operations&rdquo;|Co-Chair, ""Social Network and Platform Operations""|Chair, ""Experiment design""|Information Design and Platform Operations|PhD Mentor/Mentee Relationship Workshop|SWENext Mentorship Program|Society of Women Engineers|One of 2 student representatives" "Service page should remove session-chair items, the old reviewer residue, and the standalone Berkeley Service section."
Assert-Contains "_sass/_base.scss" "\.service-academic-panel" "Styles should define the academic services panel."
Assert-Contains "_sass/_base.scss" "\.service-academic-block" "Styles should define academic service blocks."
Assert-Contains "_sass/_base.scss" "\.service-text-list" "Styles should define readable academic service text lists."
Assert-NotContains "_sass/_base.scss" "service-compact-row|service-compact-rows" "Styles should remove the highlighted academic service row treatment."
Assert-NotContains "_sass/_base.scss" "service-inline-list" "Styles should remove the old service chip list selectors."
Assert-Contains "_sass/_base.scss" "\.service-internal-panel" "Styles should define the standalone internal-services panel."
Assert-Contains "_sass/_base.scss" "\.service-internal-group" "Styles should define CUHK and Berkeley internal service groups."
Assert-Contains "_sass/_base.scss" "\.service-item-title" "Styles should define the main service title text."
Assert-NotContains "_sass/_base.scss" "\.service-item-role" "Internal service roles should use the same title style instead of a separate color."
Assert-Contains "_sass/_base.scss" "\.service-item-meta" "Styles should define inline service metadata."
Assert-NotContains "_sass/_base.scss" 'content:\s*"/"' "Service role separators should not use a slash."
Assert-NotContains "_sass/_base.scss" 'content:\s*"\("|content:\s*"\)"' "Service roles should not be wrapped in generated parentheses."

Assert-Contains "_pages/teaching.md" "####\s*Instructor" "Teaching page should retain a clear Instructor section."
Assert-Contains "_pages/teaching.md" "####\s*Graduate Student Instructor" "Teaching page should retain a clear Graduate Student Instructor section."
Assert-Contains "_pages/teaching.md" "####\s*Mentoring" "Teaching page should include a Mentoring section."
Assert-Contains "_pages/teaching.md" "The Chinese University of Hong Kong" "Teaching page should include CUHK instructor courses."
Assert-Contains "_pages/teaching.md" "mentoring-category" "Teaching page mentoring section should group people by mentoring category."
Assert-Contains "_pages/teaching.md" ">\s*PhD Students\s*</h5>" "Teaching page mentoring section should group the listed students under PhD Students."
Assert-NotContains "_pages/teaching.md" "teaching-institution[^>]*>\s*The Chinese University of Hong Kong, DOT Department\s*</h5>" "Teaching page mentoring section should not group mentees under a shared institution line."
Assert-Contains "_pages/teaching.md" "Keyu Chen" "Teaching page mentoring section should include Keyu Chen."
Assert-Contains "_pages/teaching.md" "(?s)Keyu Chen.*The Chinese University of Hong Kong, DOT Department" "Teaching page should show Keyu Chen's institution in her own row."
Assert-Contains "_pages/teaching.md" "(?s)Keyu Chen.*Co-advisor.*Current PhD" "Teaching page mentoring section should identify Keyu Chen as a current PhD student with a co-advisor role."
Assert-Contains "_pages/teaching.md" "Chen Chen" "Teaching page mentoring section should include Chen Chen."
Assert-Contains "_pages/teaching.md" "(?s)Chen Chen.*The Chinese University of Hong Kong, DOT Department" "Teaching page should show Chen Chen's institution in his own row."
Assert-Contains "_pages/teaching.md" "(?s)Chen Chen.*Advisor.*Current PhD" "Teaching page mentoring section should identify Chen Chen as a current PhD student with an advisor role."
Assert-Contains "_pages/teaching.md" "mentoring-panel" "Teaching page mentoring section should use a distinct mentoring panel rather than course-card styling."
Assert-Contains "_pages/teaching.md" "mentoring-student" "Teaching page mentoring section should render each student as one compact row."
Assert-NotContains "_pages/teaching.md" "Co-advising|>\s*Advising\s*<|My role:" "Teaching page mentoring role wording should use advisor/co-advisor nouns without defensive labels."
Assert-NotContains "_pages/teaching.md" "class=""teaching-term"">\s*Current" "Teaching page mentoring section should not treat current status like a course term badge."
Assert-Contains "_pages/teaching.md" "DOTE 2011: Statistical Analysis for Business Decisions" "Teaching page should include DOTE 2011."
Assert-Contains "_pages/teaching.md" "Undergraduate core" "Teaching page should identify DOTE 2011 as an undergraduate core course."
Assert-Contains "_pages/teaching.md" "Fall 2024, Fall 2025, Fall 2026" "Teaching page should list the updated DOTE 2011 teaching terms clearly."
Assert-Contains "_pages/teaching.md" "DOTE 6654BA: Business Process Analytics and Simulation" "Teaching page should include DOTE 6654BA."
Assert-Contains "_pages/teaching.md" "MSc BA elective" "Teaching page should identify DOTE 6654BA as an MSc BA elective."
Assert-Contains "_pages/teaching.md" "Spring 2026" "Teaching page should include the DOTE 6654BA term."
Assert-Contains "_pages/teaching.md" "IEOR 253/CEE 258: Supply Chain and Logistics Management" "Teaching page should include the Berkeley supply chain course."
Assert-Contains "_pages/teaching.md" "E 120: Principles of Engineering Economics" "Teaching page should include E 120."
Assert-Contains "_pages/teaching.md" "IEOR 242: Applications in Data Analytics" "Teaching page should include IEOR 242."
Assert-Contains "_pages/teaching.md" "Spring 2020, Fall 2020" "Teaching page should list the IEOR 242 terms with a comma separator."
Assert-NotContains "_pages/teaching.md" "Spring 2020 & Fall 2020" "Teaching page should not use an ampersand between IEOR 242 terms."
Assert-Contains "_pages/teaching.md" "teaching-list" "Teaching page should use custom teaching list markup instead of plain tables."
Assert-Contains "_pages/teaching.md" "teaching-course" "Teaching page should render each course as a dedicated responsive row."
Assert-Contains "_pages/teaching.md" "teaching-term" "Teaching page should render terms as separate date labels."
Assert-NotContains "_pages/teaching.md" "\|\s*Course\s*\|\s*Term\s*\||6\.80/7\.00|instructor rating|Selected Student Testimonials|Department Average|Enrollment:|Ph\.D\./Master course|Undergraduate course|M\.Eng\. course|I really learn a lot" "Teaching page should remove tables, ratings, older detailed course descriptions, and testimonials."
Assert-Contains "_sass/_base.scss" "\.teaching-list" "Styles should define the custom teaching list layout."
Assert-Contains "_sass/_base.scss" "\.teaching-course" "Styles should define readable teaching course rows."
Assert-Contains "_sass/_base.scss" "(?s)\.teaching-course\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*auto" "Teaching course rows should separate long course titles from term labels without table collisions."
Assert-Contains "_sass/_base.scss" "(?s)\.teaching-institution\s*\{[^}]*color:\s*#4b1359" "Teaching institution labels should stay in the purple hierarchy instead of hard black."
Assert-NotContains "_sass/_base.scss" "(?s)\.teaching-institution\s*\{[^}]*color:\s*#111" "Instructor and Graduate Student Instructor institution labels should not use hard black."
Assert-Contains "_sass/_base.scss" "(?s)\.teaching-course-name\s*\{[^}]*color:\s*#111" "Teaching course titles should use strong black text on the light theme."
Assert-Contains "_sass/_base.scss" "(?s)\.teaching-course-code\s*\{[^}]*color:\s*#111" "Teaching course codes should use strong black text on the light theme."
Assert-Contains "_sass/_base.scss" "(?s)\.mentoring-affiliation\s*\{[^}]*color:\s*#111" "Mentee institution labels should use strong black text on the light theme."
Assert-Contains "_sass/_base.scss" "(?s)html\[data-theme=`"dark`"\]\s*\{[^}]*\.teaching-institution,\s*\.teaching-course-name,\s*\.misc-award-name,\s*\.misc-award-level,\s*\.misc-media-title\s*\{[^}]*color:\s*var\(--global-text-color\)" "Teaching institution, course titles, award names, and media titles should remain readable in dark mode."
Assert-Contains "_sass/_base.scss" "\.teaching-course-type" "Styles should define muted course-type notes after course titles."
Assert-Contains "_sass/_base.scss" "\.mentoring-panel" "Styles should define a distinct mentoring panel."
Assert-Contains "_sass/_base.scss" "(?s)\.mentoring-panel-head\s*\{[^}]*border-bottom:\s*1px" "Mentoring panel heading should use a title-style divider."
Assert-Contains "_sass/_base.scss" "(?s)\.mentoring-category\s*\{[^}]*font-size:\s*1\.05rem" "Mentoring category should read as a panel title, not as a student-name-sized label."
Assert-NotContains "_sass/_base.scss" "(?s)\.mentoring-category\s*\{[^}]*text-transform:\s*uppercase" "Mentoring category should stay title-case instead of looking like a small metadata label."
Assert-Contains "_sass/_base.scss" "(?s)\.mentoring-student\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*auto" "Mentoring student rows should keep each student compact on desktop."
Assert-Contains "_sass/_base.scss" "\.mentoring-guidance" "Styles should define the mentoring role label."
Assert-Contains "_sass/_base.scss" "\.mentoring-status" "Styles should define current PhD status labels."
Assert-Contains "_sass/_base.scss" "\.teaching-term" "Styles should define compact teaching term labels."
Assert-Contains "_sass/_base.scss" "(?s)@media \(max-width:\s*768px\).*\.teaching-course\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)" "Teaching rows should stack safely on mobile."
Assert-NotContains "_pages/about.md" "id=""clustrmaps""|clustrmaps\.com|YCvn1gfc-4Zcm16_59Td8Q8TVKH7BBu_xwEpz1zuH8E|home-visitor-map" "Homepage should not render the broken ClustrMaps dot artifact above social icons."
Assert-NotContains "_pages/about.md" "home-visitor-map-fallback" "Homepage visitor map should not use a static fallback graphic."
Assert-NotContains "_pages/about.md" "https://cdn\.clustrmaps\.com/map_v2\.js" "Homepage visitor map should not use the alternate CDN script."
Assert-NotContains "_pages/about.md" "map_v2\.png" "Homepage visitor map should not use the broken static ClustrMaps image URL."
Assert-NotContains "_pages/about.md" "####\s*Visitors" "Homepage should not show a separate Visitors heading."
Assert-NotContains "_sass/_base.scss" "\.home-visitor-map|home-visitor-map-fallback" "Homepage should not keep stale visitor map styles after removing the broken widget."

Assert-NotContains "_pages/research.md" "research-focus-list|research-overview|research-theme-grid|research-theme-card" "Research page should not repeat homepage-style agenda/theme treatments."
Assert-Contains "_pages/research.md" "####\s*Social Network Analytics and Platform Operations" "Research page should use the full social network/platform stream name as a primary section."
Assert-Contains "_pages/research.md" "####\s*AI and Machine Learning for Operations" "Research page should use the full AI and machine learning stream name as a primary section."
Assert-NotContains "_pages/research.md" "AI,\s*Optimization\s*&\s*Operational Analytics" "Research page should remove optimization from the second stream title."
Assert-Contains "_pages/research.md" "ordered from newest to oldest within each section" "Research page should explain that papers are ordered newest first within each stream."
Assert-Contains "_pages/research.md" "J=published journal, C=refereed conference, W=working paper/manuscript/work in progress" "Research page should explain the publication label system."
Assert-NotContains "_pages/research.md" "keyword chips" "Research page note should not mention removed keyword chips."
Assert-Contains "_pages/research.md" "####\s*Grants" "Research page should include grants."
Assert-Contains "_pages/research.md" "Harnessing the Power of Social Network Analytics for Enhanced Business Decision-Making" "Research page should include the CUHK hiring competitiveness grant."
Assert-Contains "_pages/research.md" "HKD 1,307,270" "Research page should include the CUHK grant amount."
Assert-Contains "_pages/research.md" "Optimal Design of the Referral Program for Two-Sided Platforms" "Research page should include the Early Career Scheme grant."
Assert-Contains "_pages/research.md" "HKD 454,062" "Research page should include the Early Career Scheme grant amount."
Assert-NotContains "_pages/research.md" 'grant-title">"' "Grant titles should not be wrapped in quotation marks."
Assert-Contains "_pages/research.md" "(?s)Social Network Analytics and Platform Operations.*AI and Machine Learning for Operations.*Grants" "Research page should list grants after the stream-organized paper sections."
Assert-Contains "_pages/research.md" "(?s)\{\%\s*include\s+paper_network\.liquid\s*\%\}.*Social Network Analytics and Platform Operations.*AI and Machine Learning for Operations.*Grants" "Research page should place the paper network before the stream-organized paper sections."
Assert-Contains "_pages/research.md" "\{\%\s*bibliography\s+--group_by\s+none\s+--query\s+@\*\[stream=social\]\*\s*\%\}" "Research page should render the social/platform stream from bibliography metadata."
Assert-Contains "_pages/research.md" "\{\%\s*bibliography\s+--group_by\s+none\s+--query\s+@\*\[stream=aiops\]\*\s*\%\}" "Research page should render the AI/analytics stream from bibliography metadata."
Assert-Contains "_pages/research.md" "\{\%\s*include\s+paper_network\.liquid\s*\%\}" "Research page should include the interactive paper network module."
Assert-Contains "_pages/research.md" "assets/js/paper-network\.js" "Research page should load the local paper network script."
Assert-Contains "_includes/paper_network.liquid" "paper-network-data" "Paper network include should expose graph data as JSON."
Assert-Contains "_includes/paper_network.liquid" "paper-network-svg" "Paper network include should render an SVG graph container."
Assert-Contains "_includes/paper_network.liquid" "My Project Network" "Paper network should use the requested section title."
Assert-NotContains "_includes/paper_network.liquid" "My Publication Network|Publication Constellation|Explore how individual papers connect through shared questions in diffusion, platform design, learning, and AI-enabled operational analytics\." "Paper network should not keep the old title or description sentence."
Assert-NotContains "_includes/paper_network.liquid" "Interactive Map|A compact view of how my papers connect" "Paper network should remove the old eyebrow and placeholder description."
Assert-Contains "_includes/paper_network.liquid" "(?s)<g class=""paper-network-viewport"">.*paper-network-zone.*paper-network-edges.*paper-network-nodes" "Paper network cluster regions should live inside the zoomed viewport with edges and nodes."
Assert-Contains "_includes/paper_network.liquid" "Social &amp; Platform" "Paper network should use a compact social/platform cluster label that avoids node overlap."
Assert-Contains "_includes/paper_network.liquid" "AI &amp; Analytics" "Paper network should use a compact AI/analytics cluster label."
Assert-NotContains "_includes/paper_network.liquid" "Related Papers|paper-network-related" "Selected-paper card should not show a related papers panel."
Assert-Contains "_includes/paper_network.liquid" "paper-network-legend" "Paper network should include a legend for similarity edge types."
Assert-Contains "_includes/paper_network.liquid" "paper-network-layer-toggle" "Paper network should expose checkbox controls for concept, method, and domain edge layers."
Assert-Contains "_includes/paper_network.liquid" "data-network-layer" "Paper network layer controls should declare their feature layer."
Assert-Contains "_includes/paper_network.liquid" "paper-network-centrality-matrix" "Selected-paper card should include a centrality matrix container."
Assert-Contains "_includes/paper_network.liquid" "paper-network-detail-features" "Selected-paper map card should keep feature keywords visible."
Assert-Contains "_includes/paper_network.liquid" "paper-network-map-insights" "Paper network map card should contain the compact leaderboard and centrality definition band."
Assert-Contains "_includes/paper_network.liquid" "paper-network-leaderboard-list" "Paper network map card should include a leaderboard list container."
Assert-Contains "_includes/paper_network.liquid" "data-network-leaderboard-metric" "Paper network leaderboard should expose metric controls so displayed values match the selected centrality metric."
Assert-Contains "_includes/paper_network.liquid" "paper-network-map-definitions" "Paper network map card should move centrality definitions into the map summary band."
Assert-NotContains "_includes/paper_network.liquid" "paper-network-legend-data" "Paper network legend should not expose data as an edge layer."
Assert-NotContains "_includes/paper_network.liquid" "paper-network-count|data-network-link-count|>\s*papers\s*<|>\s*similarities\s*<" "Paper network toolbar should remove the paper/similarity counter."
Assert-Contains "_data/paper_network.yml" "nodes:" "Paper network data should define paper nodes."
Assert-Contains "_data/paper_network.yml" "id:\s*J3" "Paper network should include the Management Science paper node."
Assert-Contains "_data/paper_network.yml" "id:\s*W6" "Paper network should include the online stochastic allocation node."
Assert-Contains "_data/paper_network.yml" "features:" "Paper network data should define grouped features for paper nodes."
Assert-Contains "_data/paper_network.yml" "concepts:" "Paper network features should include concept groups."
Assert-Contains "_data/paper_network.yml" "methods:" "Paper network features should include method groups."
Assert-Contains "_data/paper_network.yml" "domains:" "Paper network features should include domain groups."
Assert-Contains "_data/paper_network.yml" "data:" "Paper network features should include data/context groups."
Assert-Contains "_data/paper_network.yml" "social network" "Pop-up store paper should include the social network feature."
Assert-Contains "_data/paper_network.yml" "spatial network" "Pop-up store paper should include the spatial network feature."
Assert-Contains "_data/paper_network.yml" "smart city operations" "Pop-up store paper should include the smart city operations feature."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*W1.*bibkey:\s*zhang2026digitaltwin.*policy evaluation.*large-scale simulation.*multi-source data.*LLM-assisted decision-making.*\r?\n\s*-\s*simulation\s*\r?\n\s*-\s*digital twin.*social media.*social network operations.*user-generated content platform.*AI agents.*scalable network operations.*KuaiRand-Pure random-exposure data.*Tsinghua ShortVideo sampled catalogue.*VK-LSVD" "W1 should be the LLM digital twin project with its revised simulation, domain, and data features."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*W2.*status:\s*""Major revision at Production and Operations Management"".*bibkey:\s*zhong2026technology.*learning while doing.*game theory.*technology adoption.*innovation" "W2 should be technology adoption, major revision at Production and Operations Management, with the revised learning, method, and domain features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*W2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*experience-based learning\s*(?=\r?\n|$)|(?s)id:\s*W2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*dynamic modeling\s*(?=\r?\n|$)|(?s)id:\s*W2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*policy analysis\s*(?=\r?\n|$)|(?s)id:\s*W2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*technology markets\s*(?=\r?\n|$)" "W2 should not keep the older technology-adoption feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*W3.*expert decision.*decision accuracy assessment.*multi-source data.*LLM-assisted decision-making.*machine learning.*algorithm design.*design science.*Kaggle.*adult census income.*hospital readmission rates" "W3 should use the revised decision, multi-source-data, LLM-assisted decision-making, method, domain, and data features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*W3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*task-level decision accuracy\s*(?=\r?\n|$)|(?s)id:\s*W3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*decision expertise\s*(?=\r?\n|$)|(?s)id:\s*W3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*predictive modeling\s*(?=\r?\n|$)|(?s)id:\s*W3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*decision analytics\s*(?=\r?\n|$)" "W3 should not keep the older feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*J1.*real-time traffic.*crowdsourcing platform.*proprietary data from a mapping and navigation service" "J1 should use the revised traffic/crowdsourcing feature set."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*J1(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*real-time prediction\s*\r?\n|(?s)id:\s*J1(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*crowdsourcing data\s*\r?\n|(?s)id:\s*J1(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*predictive modeling\s*\r?\n" "J1 should not keep the older prediction/crowdsourcing-data/predictive-modeling feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*J2.*network diffusion.*market dynamics.*network externality.*data-driven optimization.*diffusion model.*user-generated content platform.*social media.*social network operations.*proprietary data from a short-video platform" "J2 should use the revised network diffusion, market dynamics, network externality, method, domain, and data features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*J2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*diffusion\s*\r?\n|(?s)id:\s*J2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*optimization\s*\r?\n|(?s)id:\s*J2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*short-video platform\s*\r?\n" "J2 should not keep the older generic diffusion/optimization/short-video-domain feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*J3.*network diffusion.*network structure.*network centrality.*market dynamics.*network externality.*stochastic modeling.*fixed-point iteration.*network game.*equilibrium.*agent-based simulation.*social network operations.*scalable network operations.*network repository.*Facebook network" "J3 should use the revised network, market-dynamics, network-externality, modeling, equilibrium, simulation, domain, and data features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*J3(?:(?!\r?\n  - id:).)*network influence|(?s)id:\s*J3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*optimization\s*\r?\n" "J3 should not keep the older network influence/optimization feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*C2.*physical activity monitoring.*wearable sensors.*multi-source data.*machine learning.*time series data.*transfer learning.*healthcare analytics.*mobile health.*\r?\n\s*-\s*UCI\s*\r?\n\s*-\s*daily and sports activity dataset" "C2 should use the revised wearable-sensor, multi-source-data, time-series, transfer-learning, and UCI dataset features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*C2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*adaptive learning\s*(?=\r?\n|$)|(?s)id:\s*C2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*multisource sensing\s*(?=\r?\n|$)|(?s)id:\s*C2(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*motion sensor data\s*(?=\r?\n|$)" "C2 should not keep the older adaptive-learning, multisource-sensing, or motion-sensor feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*W4.*bibkey:\s*xu2026llmagents.*\r?\n\s*-\s*simulation\s*\r?\n\s*-\s*LLM-assisted decision-making\s*\r?\n.*\r?\n\s*-\s*survey\s*\r?\n.*transportation systems.*smart city operations.*OR for AI.*AI for OR" "W4 should be the LLM agents project with the revised simulation concepts, survey method, and transportation/smart-city/OR domains."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*behavioral simulation\s*(?=\r?\n|$)|(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*platform decision support\s*(?=\r?\n|$)|(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*LLM simulation\s*(?=\r?\n|$)|(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*agent-based simulation\s*(?=\r?\n|$)|(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*transportation-enabled services\s*(?=\r?\n|$)|(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*transportation system\s*(?=\r?\n|$)|(?s)id:\s*W4(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*platform operations\s*(?=\r?\n|$)" "W4 should not keep older LLM-agents concept, simulation method, singular transportation, or platform domain wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*W5.*status:\s*""Submitted to Management Science"".*bibkey:\s*chen2026socialspatial.*dual-network.*network externality.*multi-source data.*choice model.*network game.*equilibrium.*network centrality.*data-driven optimization.*facility location.*temporal retail.*scalable network operations.*\r?\n\s*-\s*SNAP\s*\r?\n\s*-\s*Gowalla" "W5 should be the submitted social-spatial project with the revised concept, method, domain, and split dataset features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*W5(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*network choice model\s*(?=\r?\n|$)|(?s)id:\s*W5(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*SNAP Gowalla\s*(?=\r?\n|$)|(?s)id:\s*W5(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*platform operations\s*(?=\r?\n|$)" "W5 should not keep the older social-spatial method, combined dataset, or platform-operations feature wording."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*W6.*online allocation.*increasing returns.*market dynamics.*sequential decision.*learning-while-doing.*network externality.*\r?\n\s*-\s*optimization\s*\r?\n\s*-\s*competitive ratio\s*\r?\n\s*-\s*dynamic programming.*resource allocation.*platform operations.*social network operations" "W6 should use the revised sequential-decision, competitive-ratio, dynamic-programming, and social-network-operations features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*W6(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*stochastic optimization\s*(?=\r?\n|$)" "W6 should not keep stochastic optimization as a method feature."
Assert-Contains "_data/paper_network.yml" "(?s)id:\s*C3.*agent skill.*skill optimization.*Monte Carlo tree search.*bilevel optimization.*simulation optimization.*LLM-assisted optimization.*AI agents.*skill evolvement.*OR for AI" "C3 should use the revised agent-skill, optimization, simulation-optimization, and OR-for-AI features."
Assert-NotContains "_data/paper_network.yml" "(?s)id:\s*C3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*agent skill design\s*(?=\r?\n|$)|(?s)id:\s*C3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*platform decision support\s*(?=\r?\n|$)|(?s)id:\s*C3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*decision support\s*(?=\r?\n|$)|(?s)id:\s*C3(?:(?!\r?\n  - id:).)*\r?\n\s*-\s*agent-based simulation\s*(?=\r?\n|$)" "C3 should not keep the older agent-skill-design, platform-decision-support, decision-support, or agent-based-simulation feature wording."
Assert-NotContains "_data/paper_network.yml" "(?m)^edges:\s*$|relation:" "Paper network edges should be derived from features instead of listed manually."
Assert-NotContains "_data/paper_network.yml" "type:\s*(author|topic|method|venue)" "Paper network should use papers as the only node type."
Assert-Contains "assets/js/paper-network.js" "paper-network-is-zoomed" "Paper network script should reveal extra detail when zoomed."
Assert-Contains "assets/js/paper-network.js" "paper-network-detail-title" "Paper network script should update a selected-paper detail panel."
Assert-NotContains "assets/js/paper-network.js" "renderRelated|relatedList|paper-network-related" "Paper network script should not render the removed related papers panel."
Assert-Contains "assets/js/paper-network.js" "deriveSimilarityEdges" "Paper network script should derive edges from grouped paper features."
Assert-Contains "assets/js/paper-network.js" "featureGroups" "Paper network script should define the supported feature groups."
Assert-Contains "assets/js/paper-network.js" "paper-network-edge-concepts" "Paper network script should mark concept similarity edges."
Assert-Contains "assets/js/paper-network.js" "paper-network-edge-methods" "Paper network script should mark method similarity edges."
Assert-Contains "assets/js/paper-network.js" "paper-network-edge-domains" "Paper network script should mark domain similarity edges."
Assert-NotContains "assets/js/paper-network.js" "paper-network-edge-data" "Paper network script should not render data/context as a network edge layer."
Assert-Contains "assets/js/paper-network.js" "jaccardSimilarity" "Paper network script should compute layer similarity with Jaccard similarity."
Assert-Contains "assets/js/paper-network.js" "buildSimilarityMatrices" "Paper network script should build concept, method, domain, and overall adjacency matrices."
Assert-Contains "assets/js/paper-network.js" "calculateCentralityMatrix" "Paper network script should calculate a per-layer centrality matrix for each selected paper."
Assert-Contains "assets/js/paper-network.js" "calculateBetweennessCentrality" "Paper network script should compute normalized bridge scores from weighted shortest paths."
Assert-Contains "assets/js/paper-network.js" "Network Role" "Paper network script should use the approved softer centrality panel title."
Assert-Contains "assets/js/paper-network.js" "paper-network-centrality-summary" "Paper network script should render an emphasized overall network role summary."
Assert-Contains "assets/js/paper-network.js" "paper-network-centrality-layer" "Paper network script should render compact concept, method, and domain layer rows."
Assert-Contains "assets/js/paper-network.js" "paper-network-centrality-metric" "Paper network script should render centrality values as small metric blocks."
Assert-Contains "assets/js/paper-network.js" "renderNetworkLeaderboard" "Paper network script should render a compact global leaderboard inside the map card."
Assert-Contains "assets/js/paper-network.js" "paper-network-leaderboard-item" "Paper network script should render leaderboard entries by layer."
Assert-Contains "assets/js/paper-network.js" "leaderboardMetric" "Paper network script should track the selected leaderboard centrality metric."
Assert-Contains "assets/js/paper-network.js" "metrics\[leaderboardMetric\]" "Leaderboard values should come from the same degree/connectivity/bridge metrics shown in the selected-paper Network Role panel."
Assert-NotContains "assets/js/paper-network.js" "roleScore" "Leaderboard should not display a hidden composite role score."
Assert-NotContains "assets/js/paper-network.js" "paper-network-centrality-definitions|renderCentralityDefinitions|Degree centrality" "Selected-paper script should not render centrality definitions inside the detail card."
Assert-NotContains "assets/js/paper-network.js" "paper-network-centrality-table|Centrality matrix" "Paper network script should not render the rejected spreadsheet-style centrality table."
Assert-Contains "assets/js/paper-network.js" "renderFeatures" "Paper network script should render feature keywords inside the selected-paper map card."
Assert-Contains "assets/js/paper-network.js" "paper-network-feature" "Paper network script should render feature keywords inside the selected-paper map card."
Assert-Contains "assets/js/paper-network.js" "data-network-layer" "Paper network script should wire checkbox filters by layer."
Assert-Contains "assets/js/paper-network.js" "stroke-width" "Paper network script should encode within-type overlap count with edge thickness."
Assert-NotContains "assets/js/paper-network.js" "Array\.isArray\(data\.edges\)" "Paper network script should not depend on manually listed edge data."
Assert-Contains "assets/js/paper-network.js" "wheel" "Paper network script should support wheel zooming."
Assert-Contains "assets/js/paper-network.js" "pointerdown" "Paper network script should support pointer dragging/panning."
Assert-NotContains "assets/js/paper-network.js" "https?://(?!www\.w3\.org/2000/svg)" "Paper network script should be local and avoid external graph dependencies."
Assert-Contains "_sass/_base.scss" "\.paper-network-section" "Styles should define the paper network section."
Assert-Contains "_sass/_base.scss" "\.paper-network-node" "Styles should define interactive paper nodes."
Assert-Contains "_sass/_base.scss" "\.paper-network-legend" "Styles should define the paper network similarity legend."
Assert-Contains "_sass/_base.scss" "\.paper-network-map-insights" "Styles should define the compact map-level insight band."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-insights\s*\{[^}]*grid-template-columns:\s*minmax\(20rem,\s*0\.9fr\)\s*minmax\(30rem,\s*1\.05fr\)" "Paper network centrality definition column should be wider than the previous cramped layout."
Assert-Contains "_sass/_base.scss" "\.paper-network-leaderboard" "Styles should define the map-level network leaderboard."
Assert-Contains "_sass/_base.scss" "\.paper-network-leaderboard-mode" "Styles should define compact leaderboard metric controls."
Assert-Contains "_sass/_base.scss" "\.paper-network-map-definitions" "Styles should define centrality definitions inside the map card."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-label\s*\{[^}]*font-size:\s*0\.78rem" "Paper network leaderboard label should be readable."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-leaderboard-modes\s*\{[^}]*font-size:\s*0\.72rem" "Paper network leaderboard mode labels should be larger."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-leaderboard-item\s*\{[^}]*font-size:\s*0\.78rem" "Paper network leaderboard rows should be larger."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-definitions\s*\{[^}]*font-size:\s*0\.78rem" "Paper network centrality definitions should be larger."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-definition-role\s*\{[^}]*font-size:\s*0\.7rem" "Paper network centrality role labels should be larger."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-graph-frame\s*\{[^}]*height:\s*clamp\(20rem,\s*42vw,\s*28rem\)" "Paper network graph should have a bounded compact desktop height."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-svg\s*\{[^}]*height:\s*100%" "Paper network SVG should fill the bounded graph frame instead of forcing a tall graph."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-zone-label\s*\{[^}]*font-size:\s*12px" "Paper network cluster labels should be smaller and less dominant."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-node-code\s*\{[^}]*font-size:\s*13px" "Paper network node codes should be scaled down for the compact graph."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-title-label\s*\{[^}]*font-size:\s*12px" "Paper network hover labels should be smaller than the previous oversized labels."
Assert-Contains "assets/js/paper-network.js" "var view = \{ x: 0, y: 0, scale: 1 \}" "Paper network should show 100% by default."
Assert-Contains "assets/js/paper-network.js" "(?s)function resetView\(\)\s*\{[^}]*view\.x = 0;[^}]*view\.y = 0;[^}]*view\.scale = 1;" "Paper network reset should return to 100%."
Assert-NotContains "assets/js/paper-network.js" "scale: 0\.9|view\.scale = 0\.9|linkCount|data-network-link-count" "Paper network script should not keep the old 90% default or removed link counter."
Assert-Contains "_includes/paper_network.liquid" "paper-network-zoom-readout" "Paper network 100% reset should have a dedicated visual readout class."
Assert-Contains "_includes/paper_network.liquid" "Reset zoom to 100%" "Paper network 100% readout should have a clear accessible label."
Assert-Contains "_sass/_base.scss" "\.paper-network-zoom-readout" "Styles should define the 100% zoom readout as a distinct visual control."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-zoom-readout\s*\{[^}]*border-radius:\s*999px" "Project network 100% readout should look like a compact badge rather than a plain square button."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-zoom-readout\s*\{.*&::before\s*\{[^}]*border-radius:\s*999px" "Project network 100% readout should include a small reset-ring illustration."
Assert-Contains "assets/js/paper-network.js" 'class: "paper-network-node-halo", r: "25"' "Paper network halos should be smaller in the compact graph."
Assert-Contains "assets/js/paper-network.js" 'class: "paper-network-node-dot", r: "18"' "Paper network node circles should be smaller in the compact graph."
Assert-Contains "assets/js/paper-network.js" 'isRightEdgeNode \? "-28" : "28"' "Paper network title labels should sit closer to the smaller nodes."
Assert-Contains "_includes/paper_network.liquid" "paper-network-map-definition" "Map-level centrality definitions should be split into separate rows."
Assert-Contains "_includes/paper_network.liquid" "direct links" "Degree definition row should keep the short visible label requested by the user."
Assert-Contains "_includes/paper_network.liquid" "average similarity" "Connectivity definition row should keep the short visible label requested by the user."
Assert-Contains "_includes/paper_network.liquid" "shortest-path role" "Bridge definition row should keep the short visible label requested by the user."
Assert-Contains "_includes/paper_network.liquid" "Share of projects directly connected through selected similarity layers\." "Degree definition should use concise two-line wording."
Assert-Contains "_includes/paper_network.liquid" "Average weighted similarity to other projects; higher means broader overlap\." "Connectivity definition should use concise two-line wording."
Assert-Contains "_includes/paper_network.liquid" "Betweenness centrality on weighted shortest paths; higher means stronger bridge\." "Bridge definition should use concise two-line wording."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-definitions\s*\{[^}]*display:\s*grid" "Centrality definitions should stack as rows rather than inline chips."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-definition\s*\{[^}]*grid-template-columns:\s*minmax\(7\.2rem,\s*0\.28fr\)\s*minmax\(18rem,\s*1fr\)" "Centrality definition rows should widen the label and explanation columns."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-map-definition-description\s*\{[^}]*max-width:\s*31rem" "Centrality definition descriptions should have enough room to avoid three-line wrapping on desktop."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-leaderboard-entry\.is-active \.paper-network-leaderboard-code,\s*\r?\n\s*\.paper-network-leaderboard-entry\.is-active \.paper-network-leaderboard-score\s*\{[^}]*color:\s*#fff" "Active leaderboard paper labels and scores should be white on the purple highlight."
Assert-Contains "_sass/_base.scss" "\.paper-network-edge-concepts" "Styles should color concept similarity edges."
Assert-Contains "_sass/_base.scss" "\.paper-network-edge-methods" "Styles should color method similarity edges."
Assert-Contains "_sass/_base.scss" "\.paper-network-edge-domains" "Styles should color domain similarity edges."
Assert-NotContains "_sass/_base.scss" "\.paper-network-edge-data" "Styles should not keep data/context as a network edge layer."
Assert-Contains "_sass/_base.scss" "\.paper-network-layer-toggle" "Styles should define the layer checkbox controls."
Assert-Contains "_sass/_base.scss" "\.paper-network-centrality-matrix" "Styles should define the selected-paper network role panel."
Assert-Contains "_sass/_base.scss" "\.paper-network-centrality-summary" "Styles should define the emphasized overall network role summary."
Assert-Contains "_sass/_base.scss" "\.paper-network-centrality-layer-list" "Styles should define the compact layer list."
Assert-Contains "_sass/_base.scss" "\.paper-network-centrality-layer" "Styles should define concept, method, and domain layer rows."
Assert-Contains "_sass/_base.scss" "\.paper-network-centrality-metric" "Styles should define compact centrality metric blocks."
Assert-NotContains "_sass/_base.scss" "paper-network-centrality-table|paper-network-centrality-row-overall" "Styles should not keep the rejected centrality table or table-row highlight."
Assert-NotContains "_sass/_base.scss" "(?s)\.paper-network-centrality-matrix\s*\{[^}]*border-radius|(?s)\.paper-network-centrality-summary\s*\{[^}]*box-shadow|(?s)\.paper-network-centrality-summary\s*\{[^}]*border-radius" "Network role panel should be flattened instead of styled as nested cards."
Assert-NotContains "_sass/_base.scss" "\.paper-network-centrality-title::before" "Network role title should not show the rejected decorative dash."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-centrality-matrix\s*\{[^}]*border-top:\s*1px solid rgba\(196,\s*154,\s*44,\s*0\.42\)" "Network role panel should use a light divider instead of a card frame."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-centrality-summary,\s*\r?\n\s*\.paper-network-centrality-layer\s*\{[^}]*grid-template-columns:\s*minmax\(4\.6rem,\s*0\.35fr\)\s*minmax\(0,\s*1fr\)" "Overall and layer rows should share the same aligned two-column rhythm."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-centrality-summary\s*\{[^}]*background:\s*rgba\(117,\s*15,\s*109,\s*0\.13\)" "Overall network role row should use a full-row highlight instead of a fading background."
Assert-NotContains "_sass/_base.scss" "(?s)\.paper-network-centrality-summary\s*\{[^}]*border-left|(?s)\.paper-network-centrality-layer\s*\{[^}]*border-left" "Network role rows should not use leading bars or transparent gutters."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-centrality-metric\s*\{[^}]*display:\s*inline-flex" "Centrality metric labels and values should sit on the same line."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-centrality-layer-methods\s*\{[^}]*#c49a2c" "Method layer row should use the gold accent."
Assert-NotContains "_sass/_base.scss" "\.paper-network-centrality-definitions" "Styles should not keep centrality definitions inside the selected-paper detail card."
Assert-Contains "_sass/_base.scss" "\.paper-network-feature-group" "Styles should define feature keyword groups inside the selected-paper map card."
Assert-Contains "_sass/_base.scss" "\.paper-network-feature" "Styles should define compact feature keyword chips inside the selected-paper map card."
Assert-NotContains "_sass/_base.scss" "publication-keyword" "Styles should not keep visible publication-list keyword chip rules."
Assert-NotContains "_sass/_base.scss" "(?s)@media \(max-width:\s*768px\).*\.paper-network-centrality-layer\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)" "Mobile styles should not break alignment between Overall and the other role rows."
Assert-Contains "_sass/_base.scss" "(?s)\.paper-network-shell\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)" "Paper network detail card should stack under a full-width graph."
Assert-NotContains "_sass/_base.scss" "grid-template-columns:\s*minmax\(0,\s*1\.45fr\)\s*minmax\(17rem,\s*0\.78fr\)" "Paper network should not use the rejected side-by-side graph/detail layout."
Assert-NotContains "_sass/_base.scss" "min-height:\s*27rem|min-height:\s*23rem" "Paper network graph should no longer force the old tall canvas heights."
Assert-NotContains "_sass/_base.scss" "paper-network-related" "Styles should not keep rules for the removed related papers panel."
Assert-Contains "_layouts/bib.liquid" "entry\.status" "Bibliography layout should support manuscript status lines."
Assert-Contains "_layouts/bib.liquid" "entry\.status_year" "Bibliography layout should support accepted conference status lines without duplicate years."
Assert-Contains "_layouts/bib.liquid" "entry\.volume" "Bibliography layout should display volume information for published journal articles."
Assert-Contains "_layouts/bib.liquid" "entry\.award5" "Bibliography layout should display the full set of publication awards and acceptances."
Assert-Contains "_sass/_base.scss" "\.grant-list" "Styles should define the grants list."
Assert-Contains "_sass/_base.scss" "(?s)\.grant-item\s*\{[^}]*border-top:\s*1px solid" "Grant items should use publication-like divider styling."
Assert-NotContains "_sass/_base.scss" "(?s)\.grant-item\s*\{[^}]*border-radius:\s*8px|(?s)\.grant-item\s*\{[^}]*background-color:\s*rgba\(248,\s*249,\s*250" "Grant items should not use the old standalone card style."
Assert-NotContains "_layouts/bib.liquid" "publication-keywords|publication-keyword" "Publication cards should not render keyword chips."
Assert-Contains "_sass/_base.scss" "\.publication-section-title" "Styles should define distinctive publication section titles."
Assert-Contains "_sass/_base.scss" "(?s)\.research-page\s*\{.*ol\.bibliography\s*\{[^}]*display:\s*grid" "Research stream bibliographies should use a grid layout."
Assert-Contains "_sass/_base.scss" "grid-template-columns:\s*minmax\(0,\s*1fr\)" "Research publication cards should use one readable column."
Assert-NotContains "_sass/_base.scss" "grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)" "Research publication cards should not use the rejected two-column layout."
Assert-Contains "_layouts/bib.liquid" "publication-card-row" "Bibliography entries should expose a card row hook for the research grid layout."
Assert-Contains "_layouts/bib.liquid" "publication-highlight" "Publication awards and highlights should use a styled class instead of inline blue text."
Assert-NotContains "_layouts/bib.liquid" "color:#0076df" "Publication awards should not use old inline blue styling."
Assert-Contains "_layouts/bib.liquid" "entry\.label" "Bibliography layout should render J/C/W labels as the publication badge."
Assert-Contains "_sass/_base.scss" "(?s)ol\.bibliography li \.abbr abbr\s*\{[^}]*background-color:\s*#750f6d" "Publication J/C/W badges should use a visible CUHK purple fill."
Assert-Contains "_sass/_base.scss" "(?s)ol\.bibliography li \.abbr abbr\s*\{[^}]*color:\s*#fff" "Publication J/C/W badges should use white text for contrast."
Assert-Contains "_config.yml" "stream" "Custom publication stream metadata should be filtered out of public BibTeX output."
Assert-Contains "_config.yml" "keywords" "Custom publication keyword metadata should be filtered out of public BibTeX output."
Assert-NotContains "_bibliography/papers.bib" "keywords=\{[^}]*\bWIP\b[^}]*\}" "Work-in-progress should be represented by the W label/status, not by a keyword chip."

$requiredCoauthorFirstNames = @(
  "Kashish",
  "Zuo-Jun Max",
  "Heng",
  "Renyu",
  "Mengxin",
  "Shuo",
  "Haoting",
  "Jingxu",
  "Zeyu",
  "Te",
  "Linxuan",
  "Hansheng",
  "Donglin",
  "Xiangyu",
  "Zhaomiao",
  "Qixiu",
  "Jinghai",
  "Denglin",
  "Wanxue",
  "Dongcheng",
  "Weiquan",
  "Yifan",
  "Yoonsuk",
  "Qianqian",
  "Jiaming",
  "Kai",
  "Youngho",
  "Ruimin",
  "Qing"
)

foreach ($firstname in $requiredCoauthorFirstNames) {
  Assert-Contains "_data/coauthors.yml" "firstname:\s*\[[^\]]*`"$([regex]::Escape($firstname))`"" "Coauthor link map should include $firstname."
}

$intentionallyUnlinkedCoauthorFirstNames = @(
  "Chen",
  "Lingfei",
  "Chenyi"
)

foreach ($firstname in $intentionallyUnlinkedCoauthorFirstNames) {
  Assert-NotContains "_data/coauthors.yml" "firstname:\s*\[[^\]]*`"$([regex]::Escape($firstname))`"" "$firstname should remain unlinked until a verified website is available."
}

Assert-Contains "_data/coauthors.yml" "url:\s*https://shuo-ss\.github\.io/" "Shuo Sun should link to the verified personal website."
Assert-Contains "_data/coauthors.yml" "url:\s*https://scholar\.google\.com/citations\?user=lQ630oAAAAAJ&hl=en" "Haoting Zhang should link to the verified Google Scholar profile."

Assert-Contains "_bibliography/papers.bib" "A Social-Spatial Network Choice Model with Applications to Pop-Up Store Operations" "Bibliography should include the pop-up store operations manuscript."
Assert-Contains "_bibliography/papers.bib" "Beyond General Expertise: A Machine Learning Framework for Assessing Task-Level Decision Accuracy" "Bibliography should include the task-level decision accuracy manuscript."
Assert-Contains "_bibliography/papers.bib" "Technology Adoption under Experience-Based Learning: A Dynamic Market and Policy Analysis" "Bibliography should include the technology adoption manuscript."
Assert-Contains "_bibliography/papers.bib" "LLM-Augmented Digital Twin for Policy Evaluation in Short-Video Platforms" "Bibliography should include the short-video platforms manuscript."
Assert-Contains "_bibliography/papers.bib" "LLM Agents in Transportation-enabled Service Platforms" "Bibliography should include the LLM agents service platforms manuscript."
Assert-Contains "_bibliography/papers.bib" "Accepted to 25th ACM Conference on Economics and Computation, 2024" "Bibliography should include all listed acceptances for the nonprogressive diffusion paper."
Assert-Contains "_bibliography/papers.bib" "Finalist, INFORMS Minority Issues Forum Paper Competition, 2024" "Bibliography should include the MSOM paper's 2024 finalist award."
Assert-Contains "_bibliography/papers.bib" "category=\{journal\}" "Journal bibliography entries should be tagged with the journal category."
Assert-NotContains "_bibliography/papers.bib" "Lin\*" "Bibliography author names should not display corresponding-author asterisks."
Assert-NotContains "_bibliography/papers.bib" "abbr=\{" "Publication badges should come from J/C/W labels instead of abbr topic badges."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{lin2020traffic,[^@]*label=\{J1\}" "Oldest published journal paper should be labeled as J1."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{lin2024content,[^@]*label=\{J2\}" "Published MSOM paper should be labeled as J2."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{lin2025nonprogressive,[^@]*label=\{J3\}" "Published Management Science paper should be labeled as J3."
Assert-NotContains "_bibliography/papers.bib" "label=\{J[4-9]\}" "Unpublished manuscripts should not use journal-paper labels."
Assert-Contains "_bibliography/papers.bib" "(?s)@inproceedings\{zheng2020collimatorless,[^@]*label=\{C1\}" "Oldest conference paper should be labeled as C1."
Assert-Contains "_bibliography/papers.bib" "(?s)@inproceedings\{zhang2024activity,[^@]*label=\{C2\}" "CHIL conference paper should be labeled as C2."
Assert-Contains "_bibliography/papers.bib" "(?s)@inproceedings\{huang2026bilevel,[^@]*label=\{C3\}" "WSC conference paper should be labeled as C3."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{zhang2026digitaltwin,[^@]*label=\{W1\}" "LLM digital twin manuscript should start the working-paper labels."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{zhong2026technology,[^@]*label=\{W2\}[^@]*status=\{Major Revision\}[^@]*target=\{Production and Operations Management\}" "Technology adoption should be W2 and major revision at Production and Operations Management."
Assert-NotContains "_bibliography/papers.bib" "(?s)@article\{zhong2026technology,[^@]*abstract_id=7287358" "Technology adoption should not carry the social-spatial SSRN link."
Assert-NotContains "_bibliography/papers.bib" "(?s)@article\{zhong2026technology,[^@]*status=\{Submitted to\}[^@]*target=\{Management Science\}" "Technology adoption should not render as 'Submitted to at Management Science'."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{dong2026expertise,[^@]*label=\{W3\}" "Under-review manuscript should be labeled as a working paper."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{xu2026llmagents,[^@]*label=\{W4\}" "LLM agents manuscript should be W4."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{chen2026socialspatial,[^@]*label=\{W5\}[^@]*status=\{Submitted to Management Science\}[^@]*ssrn=\{https://papers\.ssrn\.com/sol3/papers\.cfm\?abstract_id=7287358\}" "Social-spatial manuscript should be W5, submitted to Management Science, and link to SSRN."
Assert-NotContains "_bibliography/papers.bib" "(?s)@article\{chen2026socialspatial,[^@]*status=\{Ready to submit\}" "Social-spatial manuscript should not keep the ready-to-submit status."
Assert-Contains "_bibliography/papers.bib" "(?s)@misc\{sun2026allocation,[^@]*label=\{W6\}" "Work-in-progress project should continue the working-paper labels."
Assert-Contains "_bibliography/papers.bib" "(?s)@misc\{sun2026allocation,[^@]*stream=\{social\}" "Online stochastic allocation should appear in the first research stream."
Assert-Contains "_bibliography/papers.bib" "(?s)@misc\{sun2026allocation,[^@]*year=\{2026\}" "Online stochastic allocation should display the 2026 year."
Assert-Contains "_bibliography/papers.bib" "(?s)@article\{chen2026socialspatial,.*@article\{zhong2026technology,.*@article\{lin2025nonprogressive,.*@article\{lin2024content,.*@misc\{sun2026allocation,.*@inproceedings\{huang2026bilevel,.*@article\{xu2026llmagents,.*@article\{zhang2026digitaltwin,.*@article\{dong2026expertise,.*@inproceedings\{zhang2024activity,.*@inproceedings\{zheng2020collimatorless,.*@article\{lin2020traffic," "Bibliography source order should render each research stream from newer to older while keeping labels unchanged."
Assert-Contains "_bibliography/papers.bib" "stream=\{social\}" "Bibliography should mark the social/platform stream."
Assert-Contains "_bibliography/papers.bib" "stream=\{aiops\}" "Bibliography should mark the AI/analytics stream."
Assert-Contains "_bibliography/papers.bib" "keywords=\{Networks; Platforms\}" "Bibliography should use a small representative keyword set."
Assert-Contains "_bibliography/papers.bib" "Bilevel Optimization of Agent Skills via Monte Carlo Tree Search" "Bibliography should include the WSC proceedings paper."
Assert-Contains "_bibliography/papers.bib" "Daily Physical Activity Monitoring---Adaptive Learning from Multi-source Motion Sensor Data" "Bibliography should include the CHIL proceedings paper."
Assert-Contains "_bibliography/papers.bib" "Collimatorless Scintigraphy for Imaging Extremely Low Activity Targeted Alpha Therapy" "Bibliography should include the MICCAI proceedings paper."
Assert-Contains "_bibliography/papers.bib" "Online Stochastic Allocation with Increasing Returns" "Bibliography should include the work-in-progress allocation project."
Assert-Contains "_bibliography/papers.bib" "category=\{conference\}" "Conference bibliography entries should be tagged with the conference category."
Assert-Contains "_bibliography/papers.bib" "category=\{progress\}" "Work-in-progress bibliography entries should be tagged with the progress category."

$removedPages = @(
  "_pages/publications.md",
  "_pages/cv.md",
  "_pages/news.md"
)

foreach ($page in $removedPages) {
  if (Test-Path $page) {
    throw "Removed page should not exist: $page"
  }
}

Assert-NotContains "_data/cv.yml" "Albert Einstein|Nobel Prize|Theoretical Physics" "CV data still contains al-folio placeholder content."
Assert-NotContains "assets/json/resume.json" "Albert Einstein|Theoretical Physics|Quantum" "JSON resume still contains al-folio placeholder content."
Assert-NotContains "README.md" "^#\s+al-folio" "README still starts with upstream al-folio content."
Assert-NotContains "README.md" "publications, teaching, service, and CV" "README should describe the current page structure."

Assert-NoFiles "_posts" "Demo blog posts should be removed."
Assert-NoFiles "_projects" "Demo project pages should be removed."
Assert-NoFiles "_news" "News items should be removed."

$demoPaths = @(
  "assets/img/readme_preview",
  "assets/audio/epicaly-short-113909.mp3",
  "assets/video/pexels-engin-akyurt-6069112-960x540-30fps.mp4",
  "assets/jupyter/blog.ipynb",
  "assets/plotly/demo.html",
  "assets/pdf/example_pdf.pdf",
  "lighthouse_results",
  "reports"
)

foreach ($path in $demoPaths) {
  if (Test-Path $path) {
    throw "Demo artifact should be removed: $path"
  }
}

$workflowFiles = Get-ChildItem ".github/workflows" -File | Select-Object -ExpandProperty Name
$expectedWorkflows = @("deploy.yml", "preview.yml")
$unexpectedWorkflows = $workflowFiles | Where-Object { $expectedWorkflows -notcontains $_ }
if ($unexpectedWorkflows.Count -gt 0) {
  throw "Unexpected upstream workflows remain: $($unexpectedWorkflows -join ', ')"
}

Assert-Contains ".github/workflows/preview.yml" "branches:\s*\r?\n\s*-\s*codex/site-refresh" "Preview workflow should run only from codex/site-refresh."
Assert-Contains ".github/workflows/preview.yml" "\*\*/\*\.scss|_sass/\*\*" "Preview workflow should rebuild after style-only changes."
Assert-Contains ".github/workflows/preview.yml" "_plugins/\*\*" "Preview workflow should rebuild after plugin changes."
Assert-Contains ".github/workflows/preview.yml" "--baseurl /preview/site-refresh" "Preview workflow should build with the preview baseurl."
Assert-Contains ".github/workflows/preview.yml" "target-folder:\s*preview/site-refresh" "Preview workflow should deploy into the gh-pages preview folder."
Assert-Contains ".github/workflows/preview.yml" "clean:\s*false" "Preview workflow should not clean the live gh-pages root."
Assert-NotContains ".github/workflows/deploy.yml" "(?m)^\s*pull_request:" "Deploy workflow should not run on pull requests; preview.yml handles refresh-branch builds."
Assert-Contains ".github/workflows/deploy.yml" "\*\*/\*\.scss|_sass/\*\*" "Deploy workflow should rebuild after style-only changes."
Assert-Contains ".github/workflows/deploy.yml" "_plugins/\*\*" "Deploy workflow should rebuild after plugin changes."

Write-Host "Site refresh validation passed."
